### ISSUE TITLE
Problem with import of Popper module due to case sensitiveness

### ISSUE THREAD

**Issue by polakluk** [souporserious/react-popper#95] opened 2018-02-23 16:54 UTC
Hi,

we recently tried to upgrade react-popper to its newer version (1.2.9), but ran into an issue. On Windows 10 with Webpack 3.11.0. and Webpack-dev-server 2.11.1, it shows following warning

```
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* path-to-code\node_modules\react-popper\lib\Popper.js
    Used by 1 module(s), i. e.
    path-to-code\node_modules\react-popper\lib\react-popper.js
* path-to-code\node_modules\react-popper\lib\popper.js
    Used by 2 module(s), i. e.
    path-to-code\node_modules\react-popper\lib\Popper.js
```

This can be fixed by changing line 19 (in file `lib\Popper.js` ) from:

```
var _popper = require('popper.js');
```

to

```
var _popper = require('Popper.js');
```

**Comment by polakluk** [comment] 2018-02-24 18:29
After I played with the issue a while and found out that this is not caused by the first uppercased character. The intention there is to require module `popper.js` and not file `Popper.js` which is in the same directory. Could this file be renamed in this project so it would work on Windows as well?

**Comment by supergibbs** [comment] 2018-02-26 22:17
This should def be fixed but in the meantime you can look into using the Windows 10 linux subsystem. 

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by polakluk** [comment] 2018-03-05 10:16
@supergibbs thank you! For now, we can definitely stay with the older version. If there is a way we can help you fix it, let me know.

**Comment by meet-aleksey** [comment] 2018-03-10 13:53
Hi!

How I can fix this in Windows? 

Using Linux is not possible, because this makes the project not portable.

**Comment by FezVrasta** [comment] 2018-03-19 14:58
This seems a dupe of #76

**Closed by FezVrasta** 2018-03-19 14:58 UTC

**Comment by kieranbenton** [comment] 2019-03-11 15:26
@FezVrasta this is still an issue - I've just run into it myself getting stood up with reactstrap. I believe this, #76 and #111 are all related (and indeed it might be on windows only which is why you don't seem to see the issue).

Fundamentally I actually agree technically (if not how it was put to you by @PurpleGranite which was unacceptable) the solution in #111 of renaming the ```Popper.js``` file in your module to something else that won't conflict with the 'real' `popper.js' npm module. Its not workable to force everyone who uses your library to either not use windows and/or to only use relative path module resolution in webpack, and this isn't an isolated problem as I can tell by the number of issues related to it! Its not fair to say that this is an edge case either, we're talking about a naming conflict between your library and the library it itself depends upon! :)

That being said - for everyone else who is having this issue or working around it, I've found a much cleaner solution that just targets this specific problem and doesnt force you to change the way you use module resolution in webpack wholesale.

Add to your webpack config an alias for ```popper.js``` that forces the node_modules version to be used and not the file in the local path.

e.g.
```
	resolve: {
		alias: {
			"popper.js": "popper.js/dist/esm/popper.js" // see - https://github.com/FezVrasta/react-popper/issues/111
		},
		modules: ["./", "node_modules"],
		extensions: [".tsx", ".ts", ".js", ".css", ".scss"]
	},
```

**Comment by FezVrasta** [comment] 2019-03-11 16:38
@kieranbenton thanks for the time you took to write this post.

My point is that something **very** wrong is happening on these webpack configs, react-popper throws an error and we call it a day. But there may be subtle issues that don't get noticed at first and that may break stuff more seriously down the road.

react-popper isn't doing anything wrong, and it's not "fixing" my library the way to handle the webpack issue you guys are having.
